# Generated by Django 5.2.3 on 2025-06-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_alter_proyecto_claveinterna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='claveCarrera',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='action',
            field=models.BooleanField(default=False),
        ),
    ]
