# Generated by Django 5.2.3 on 2025-06-23 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0002_alter_carrera_clavecarrera'),
        ('proyecto', '0003_remove_proyecto_clavecarrera_proyecto_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='action',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='claveCarrera',
            field=models.ForeignKey(blank=True, db_column='claveCarrera', null=True, on_delete=django.db.models.deletion.CASCADE, to='carrera.carrera'),
        ),
    ]
