# Generated by Django 5.2.3 on 2025-06-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_remove_proyecto_action_proyecto_clavecarrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='action',
            field=models.BooleanField(default=False),
        ),
    ]
