# Generated by Django 5.2.3 on 2025-07-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_proyecto_action'),
        ('proyecto', '0005_proyecto_metas'),
    ]

    operations = [
    ]
