# Generated by Django 5.2.3 on 2025-07-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_merge_0005_proyecto_action_0005_proyecto_metas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='action',
        ),
    ]
