# Generated by Django 5.2.3 on 2025-07-03 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_remove_proyecto_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='rfc_Empresa',
            new_name='rfc',
        ),
    ]
