# Generated by Django 5.2.3 on 2025-07-03 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_remove_empresa_proyectos'),
        ('proyecto', '0008_rename_rfc_empresa_proyecto_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='rfc',
            field=models.ForeignKey(db_column='rfc', on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
    ]
