# Generated by Django 5.2.3 on 2025-07-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0004_remove_estudiante_claveproyecto'),
        ('proyecto', '0009_alter_proyecto_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estudiante',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='estudiante.estudiante'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estatusProyecto',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8, null=True),
        ),
    ]
