# Generated by Django 5.2.3 on 2025-07-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('proyecto', '0010_proyecto_estudiante_alter_proyecto_estatusproyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='colaboradorProyecto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='colaborador',
            field=models.ManyToManyField(blank=True, related_name='proyecto', to='colaboradores.colaboradores'),
        ),
    ]
