# Generated by Django 5.2.3 on 2025-07-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('investigador', '0005_alter_investigador_correo'),
        ('proyecto', '0011_remove_proyecto_colaboradorproyecto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='colaborador',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, null=True, related_name='proyectos_colaborados', through='colaboradores.Colaboradores', to='investigador.investigador'),
        ),
    ]
