# Generated by Django 5.2.3 on 2025-07-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('investigador', '0005_alter_investigador_correo'),
        ('proyecto', '0012_remove_proyecto_colaborador_proyecto_colaboradores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='proyectos_colaborados', through='colaboradores.Colaboradores', to='investigador.investigador'),
        ),
    ]
