# Generated by Django 5.2.3 on 2025-07-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0013_alter_proyecto_colaboradores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
