# Generated by Django 5.2.3 on 2025-07-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_alter_proyecto_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='action',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
