# Generated by Django 5.2.3 on 2025-07-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0015_proyecto_action_alter_proyecto_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fechaFinFinanciamiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fechaInicioFinanciamiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipoProyecto',
            field=models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('Continuidad', 'Continuidad')], default='Nuevo', max_length=12, null=True),
        ),
    ]
