# Generated by Django 5.2.3 on 2025-07-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_proyecto_fechafinfinanciamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='quienFinancia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
