# Generated by Django 5.2.3 on 2025-07-01 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='convocatoria',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='El formato del nombre de la convocatoria no es válido', regex='^[\\w\\s\\.\\&\\-\\u00C0-\\u00FF?¡!¿:;|@]+$')]),
        ),
    ]
