# Generated by Django 5.2.3 on 2025-10-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0004_convocatoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='requisitos',
            field=models.TextField(blank=True, error_messages={'max_length': 'Los requisitos no pueden exceder 500 caracteres.'}, max_length=500, null=True),
        ),
    ]
