# Generated by Django 5.2.3 on 2025-07-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
