# Generated by Django 5.2.3 on 2025-06-27 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credenciales', '0002_remove_credenciales_contraseña_and_more'),
        ('investigador', '0002_investigador_user_alter_investigador_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='id_Credencial',
            field=models.ForeignKey(blank=True, db_column='id_Credencial', null=True, on_delete=django.db.models.deletion.CASCADE, to='credenciales.credenciales'),
        ),
    ]
