# Generated by Django 5.2.3 on 2025-07-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0002_alter_investigador_fecha_registro'),
        ('investigador', '0003_alter_investigador_id_credencial'),
    ]

    operations = [
    ]
