# Generated by Django 5.2.3 on 2025-07-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigador', '0004_merge_20250702_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='correo',
            field=models.CharField(max_length=100),
        ),
    ]
