# Generated by Django 5.2.3 on 2025-09-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigador', '0001_initial'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigador.investigador')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboraciones', to='proyecto.proyecto')),
            ],
        ),
    ]