# Generated by Django 5.2.3 on 2025-06-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='semestre',
            field=models.CharField(default='1', max_length=90),
        ),
    ]
