# Generated by Django 5.2.3 on 2025-06-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_estudiante_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='semestre',
            field=models.CharField(max_length=90),
        ),
    ]
