# Generated by Django 5.2.3 on 2025-07-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_alter_estudiante_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='claveProyecto',
        ),
    ]
