# Generated by Django 5.2.3 on 2025-06-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metas',
            name='cantidad',
        ),
    ]
