# Generated by Django 5.2.3 on 2025-07-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0002_remove_metas_cantidad'),
        ('metas', '0003_remove_metas_proyecto'),
    ]

    operations = [
    ]
