# Generated by Django 5.2.3 on 2025-07-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('proyecto', '0007_remove_proyecto_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='proyectos',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='proyecto.proyecto'),
        ),
    ]
