# Generated by Django 5.2.3 on 2025-07-03 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_proyectos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='proyectos',
        ),
    ]
